project:
  type: website

website:
  title: "VA Project - Group 4"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: The Team
      - icon: github
        href: https://github.com/sonphamsmu/isss608-vaa-project
    left:
      - text: Overview
        menu: 
          - href: overview/proposal/proposal.html
            text: Project Proposal  
      - text: Shiny App
        menu: 
          - text: Shiny App
            href: "https://edwardbyl.shinyapps.io/AChickenRiceStory/"
          - text: User Guide
      - text: Modules
        menu: 
          - text: EDA
            href: "https://sonpham-isss608-vaa-jan2526.netlify.app/takehome_ex/takehome2/takehome_ex2"
          - text: Clustering
            href: "https://edwardbyl.netlify.app/take-home_ex/take-home_ex02/take-home_ex02"
          - text: Prediction
            href: "https://isss608-visual.netlify.app/take-home_ex/take-home_ex2/take-home_ex2"
            
  page-navigation: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true

editor: visual

